[project]
name = 'Blockchain-Based-Advanced-Manufacturing-Traceability-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.assembly-tracking]
path = 'contracts/assembly-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.digital-passport]
path = 'contracts/digital-passport.clar'
clarity_version = 2
epoch = 2.5

[contracts.material-certification]
path = 'contracts/material-certification.clar'
clarity_version = 2
epoch = 2.5

[contracts.quality-verification]
path = 'contracts/quality-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.supplier-verification]
path = 'contracts/supplier-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
